name: Harvest ESG leads

permissions:
  contents: write

on:
  schedule:
    # Runs daily at 01:00 UTC (~06:30 IST)
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  harvest:
    runs-on: ubuntu-latest
    concurrency:
      group: gb2b-harvest
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests pandas beautifulsoup4 xlsxwriter

      - name: Run harvester
        - name: Run harvester
  env:
    SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}     # optional
    BING_API_KEY: ${{ secrets.BING_API_KEY }}   # optional
    BING_ENDPOINT: "https://api.bing.microsoft.com/v7.0/search"
    NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}     # <-- add this line
  run: |
    python lead_harvester.py

      - name: Commit CSV/XLSX back to repo
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gb2b_leads.csv gb2b_leads.xlsx || true
          git diff --cached --quiet && echo "No changes to commit." || git commit -m "chore: update leads CSV/XLSX"
          git push
